<?php

namespace Database\Seeders;

use App\Enums\User\Type;
use App\Models\Admin;
use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class AdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminPermissions = [
            "create_address",
            "create_admin",
            // "create_attribute",
            "create_bank",
            "create_bank::account",
            "create_branch",
            "create_brand",
            "create_category",
            "create_coupon",
            "create_f::a::q",
            "create_order::item",
            "create_order::return",
            // "create_pending::provider",
            "create_pending::vendor",
            "create_product",
            // "create_product::variant",
            // "create_provider",
            "create_role",
            "create_seller",
            "create_slider",
            "create_unit",
            "create_user",
            "create_vendor",
            "create_wallet::transaction::deposit",
            "delete_address",
            "delete_admin",
            // "delete_any_attribute",
            "delete_any_branch",
            "delete_any_category",
            "delete_any_order::item",
            "delete_any_order::return",
            // "delete_any_pending::provider",
            "delete_any_pending::vendor",
            // "delete_any_product::variant",
            "delete_any_role",
            "delete_any_vendor",
            "delete_any_wallet::transaction::deposit",
            // "delete_attribute",
            "delete_bank",
            "delete_bank::account",
            "delete_branch",
            "delete_brand",
            "delete_category",
            "delete_contact",
            "delete_coupon",
            "delete_f::a::q",
            "delete_invoice",
            "delete_order::item",
            "delete_order::return",
            // "delete_pending::provider",
            "delete_pending::vendor",
            "delete_product",
            'create_vendor::product',
            'update_vendor::product',
            'delete_vendor::product',
            'restore_vendor::product',
            'view_vendor::product',
            'view_any_vendor::product',
            // "delete_product::variant",
            // "delete_provider",
            "delete_review",
            "delete_role",
            "delete_seller",
            "delete_slider",
            "delete_ticket",
            "delete_unit",
            "delete_user",
            "delete_vendor",
            "delete_wallet::transaction",
            "delete_wallet::transaction::deposit",
            "force_delete_address",
            "force_delete_admin",
            // "force_delete_any_attribute",
            "force_delete_any_branch",
            "force_delete_any_category",
            "force_delete_any_order::item",
            "force_delete_any_order::return",
            // "force_delete_any_pending::provider",
            "force_delete_any_pending::vendor",
            // "force_delete_any_product::variant",
            "force_delete_any_role",
            "force_delete_any_vendor",
            "force_delete_any_wallet::transaction::deposit",
            // "force_delete_attribute",
            "force_delete_bank",
            "force_delete_bank::account",
            "force_delete_branch",
            "force_delete_brand",
            "force_delete_category",
            "force_delete_contact",
            "force_delete_coupon",
            "force_delete_invoice",
            "force_delete_order",
            "force_delete_order::item",
            "force_delete_order::return",
            // "force_delete_pending::provider",
            "force_delete_pending::vendor",
            "force_delete_product",
            // "force_delete_product::variant",
            // "force_delete_provider",
            "force_delete_review",
            "force_delete_role",
            "force_delete_seller",
            "force_delete_ticket",
            "force_delete_unit",
            "force_delete_user",
            "force_delete_vendor",
            "force_delete_wallet::transaction",
            "force_delete_wallet::transaction::deposit",
            "page_MyProfilePage",
            "page_Settings",
            // "reorder_attribute",
            "reorder_branch",
            "reorder_category",
            "reorder_order::item",
            "reorder_order::return",
            // "reorder_pending::provider",
            "reorder_pending::vendor",
            // "reorder_product::variant",
            "reorder_role",
            "reorder_vendor",
            "reorder_wallet::transaction::deposit",
            // "replicate_attribute",
            "replicate_branch",
            "replicate_category",
            "replicate_order::item",
            "replicate_order::return",
            // "replicate_pending::provider",
            "replicate_pending::vendor",
            // "replicate_product::variant",
            "replicate_role",
            "replicate_vendor",
            "replicate_wallet::transaction::deposit",
            "restore_address",
            "restore_admin",
            // "restore_any_attribute",
            "restore_any_branch",
            "restore_any_category",
            "restore_any_order::item",
            "restore_any_order::return",
            // "restore_any_pending::provider",
            "restore_any_pending::vendor",
            // "restore_any_product::variant",
            "restore_any_role",
            "restore_any_vendor",
            "restore_any_wallet::transaction::deposit",
            // "restore_attribute",
            "restore_bank",
            "restore_bank::account",
            "restore_branch",
            "restore_brand",
            "restore_category",
            "restore_contact",
            "restore_coupon",
            "restore_invoice",
            "restore_order",
            "restore_order::item",
            "restore_order::return",
            // "restore_pending::provider",
            "restore_pending::vendor",
            "restore_product",
            // "restore_product::variant",
            // "restore_provider",
            "restore_review",
            "restore_role",
            "restore_seller",
            "restore_ticket",
            "restore_unit",
            "restore_user",
            "restore_vendor",
            "restore_wallet::transaction",
            "restore_wallet::transaction::deposit",
            "translation",
            "update_address",
            "update_admin",
            // "update_attribute",
            "update_bank",
            "update_bank::account",
            "update_branch",
            "update_brand",
            "update_category",
            "update_coupon",
            "update_f::a::q",
            "update_order::item",
            "update_order::return",
            // "update_pending::provider",
            "update_pending::vendor",
            "update_product",
            // "update_product::variant",
            // "update_provider",
            "update_role",
            "update_seller",
            "update_slider",
            "update_unit",
            "update_user",
            "update_vendor",
            "update_wallet::transaction::deposit",
            "view_activitylog",
            "view_admin",
            "view_any_activitylog",
            "view_any_address",
            "view_any_admin",
            // "view_any_attribute",
            "view_any_bank",
            "view_any_bank::account",
            "view_any_branch",
            "view_any_brand",
            "view_any_category",
            "view_any_contact",
            "view_any_coupon",
            "view_any_f::a::q",
            "view_any_invoice",
            "view_any_order",
            "view_any_order::item",
            "view_any_order::return",
            // "view_any_pending::provider",
            "view_any_pending::vendor",
            "view_any_product",
            // "view_any_product::variant",
            // "view_any_provider",
            "view_any_review",
            "view_any_role",
            "view_any_seller",
            "view_any_slider",
            "view_any_ticket",
            "view_any_unit",
            "view_any_user",
            "view_any_vendor",
            "view_any_wallet::transaction",
            "view_any_wallet::transaction::deposit",
            // "view_attribute",
            "view_branch",
            "view_category",
            "view_coupon",
            "view_order",
            "view_order::item",
            "view_order::return",
            // "view_pending::provider",
            "view_pending::vendor",
            // "view_product::variant",
            "view_role",
            "view_vendor",
            "view_wallet::transaction",
            "view_wallet::transaction::deposit",
            // "widget_UserMultiWidget"
        ];
        foreach ($adminPermissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'admin']);
        }

        $adminRole = Role::firstOrCreate(['name' => 'Admin', 'guard_name' => 'admin']);
        $adminRole->syncPermissions(Permission::where('guard_name', 'admin')->get());

        $adminUser = User::firstOrCreate(
            [
                'type' => Type::ADMIN,
                'email' => 'samir@admin.com',
            ],
            [
                'name' => 'Samir',
                'type' => Type::ADMIN,
                'email' => 'samir@admin.com',
                'password' => bcrypt('123456789'),
            ]
        );

        $adminUser->assignRole($adminRole);

        $this->command->info('Seeder has successfully created an admin user with all permissions.');
    }
}
